config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :admins

  resources :cvs

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_many :projects
end

app/models/cv.rb
class Cv < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
	belong_to :admin
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
  end

  # GET /admins/new
  def new
    @admin = Admin.new
  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_url, notice: 'Admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
      params.require(:admin).permit(:name, :pic_url, :email, :skills)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/cvs_controller.rb
class CvsController < ApplicationController

	def index

	end

end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  def index
    @admin = Admin.last
  end


  private

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pic_url %><br>
    <%= f.text_field :pic_url %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :skills %><br>
    <%= f.text_field :skills %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<div id="wrap">
  <h1>Welcome Back</h1>


  <%= link_to 'New Admin', new_admin_path %>

</div>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Pic url:</strong>
  <%= @admin.pic_url %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @admin.skills %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/cvs/index.html.erb
<div id="clip">
	<div id="intro-page"
		data-0="top: 0;"
		data-1000="top:0;"
		data-1200="top: -50px;"
		data-1400="top: -200px;"
		data-1700="top: -300px;"
		data-1900="top: -400px;"
		data-2100="top: -500px;"
		data-2300="top: -600px;"
		data-2500="top: -750px;" >
		<div class="logo-cell">
			<span class="logo skrollable rendered"
				data--10="top:10px;"
				data-600="top:32px;" >
				<%=image_tag("airscrew.png") %>
			</span>
		</div>
		<div class="tringle-bar"
			data--10="top:-190px;"
			data-350="top:-150px;"
			data-1000="top: -150px;"
			data-1900="top: -160px;" >
			<%=image_tag("tringle-top.png") %>
		</div>
		<div class="plane"
			data-300="top: -10px; transform[bounce]:scale(0.4); opacity: 1;"
			data-1000="top:1000px;transform[bounce]:scale(1.5); opacity: 1;"
			data-1300="top:1000px;transform[bounce]:scale(1.5); opacity: 0;">
			<%=image_tag("air-top.svg") %>
			<span class="airscrew"></span>
		</div>
		<div class="tringle-back">
			<%=image_tag("tringle-top.svg") %>
		</div>
		<div class="self-box"
			data-0="top: 0px; "
			data-400="top: -60px;">
			<div class="self-cnt"
				data-0="top: 300px; opacity: 1;"
				data-400="top: 400px; opacity: 0.6;"
				data-1200="top: 420px; opacity: 0;">
				<div class="cnt-bg"></div>
				<div class="photo-box">
					<%=image_tag("logo-self.png", class: "photo") %>
				</div>
				<div class="who-am-i">
					<h2><%= @admin.name %></h2>
					<h3>正在起飞的前端工程师</h3>
					<p>
						<a href="mailto:<%= @admin.email%>" class="strang email">EMAIL</a>
					</p>
				</div>
			</div>
			<div class="road-box">
				<div class="road-line"
					data-140="top: 0px;"
					data-2000="top: -4000px;"></div>
			</div>
			<%=image_tag("tringle-large-top.png", class: "bottom") %>

		</div>
		<div class="about-me"
			data-300="top: -800px;"
			data-1000="top: -50px;"
			data-1900="top: -300px;" >
			<ul>
				<li><span>姓名&nbsp;|&nbsp;</span><%= @admin.name %></li>
				<li><span>手机&nbsp;|&nbsp;</span><%= @admin.phone %></li>
				<li><span>邮箱&nbsp;|&nbsp;</span><a href="mailto:<%= @admin.email%>"><%= @admin.email%></a></li>
				<li><span>博客&nbsp;|&nbsp;</span><a href="<%= @admin.blog_url %>">欢迎猛击</a></li>
				<li><span>教育背景&nbsp;|&nbsp;</span><%= @admin.edu_info %></li>
				<% if false %>
				<li><span>GitHub&nbsp;|&nbsp;</span><a href="<%= @admin.github_url%>">欢迎猛击</a></li>
				<% end %>
			</ul>
			<div class="introduction">
				<p>今夏最适合出境游的目的地是哪？当然是欧洲！
				受欧洲政经形势和国际市场多重因素的影响，欧元对人民币的汇率跌破7.0大关，创下了欧元诞生以来的历史最低；同时，很多国家大使馆也进一步放宽了旅游签证的条件。钱不是问题，签证也不是问题，还有比这个时候更适合去欧洲的吗？
				无论你是向往西方文明的印迹，或是只想吃吃吃买买买；无论你是早已去过那些耳熟能详热门景点的旅行达人，或只是一个蠢蠢欲动的出境游小白，都可以试试下面这几个欧洲小众目的地。
				</p>
			</div>
			<div class="star star-top-left">
				<%= image_tag("star.png") %>
			</div>
			<div class="star star-top-right">
				<%= image_tag("star.png") %>
			</div>
			<div class="star star-bottom-left">
				<%= image_tag("star.png") %>
			</div>
			<div class="star star-bottom-right">
				<%= image_tag("star.png") %>
			</div>
			<%=image_tag("about-me-bottom.png", class: "bottom") %>
		</div>
		<div class="clouds-bar">
			<div class="cloud-1"
				data-0="left: 150px;"
				data-1500="left: 350px;"
				data-3000="left: 150px" >
				<%= image_tag("cloud-1.svg", height: 171 )%>
			</div>
			<div class="cloud-2"
				data-0="right: 50px;"
				data-1500="right: 350px;"
				data-3000="right: 50px"
				>
				<%= image_tag("cloud-2.svg", height: 171 )%>
			</div>
		</div>
	</div>
	<idv id="skills-page" data-1300="top:200px" data-1700="top: 0px" >

	</idv>
</div>
<script>

	var scrollObj = skrollr.init({
		  //跟smoothScrolling的功能，主要都是讓scroll事件不要這麼敏感，動畫才不會看起來卡卡的。
		  smoothScrolling : true,
		  smoothScrollingDuration:200,

	});
	var $email = $('.email');
	$email.on("mouseenter", function(){
		$email.fadeOut("slow","swing",function(){
			$email.text("yundong.me@gmail.com");
			$email.fadeIn("slow","swing");
		});
	});
	$email.on("mouseout", function(){
		$email.fadeOut("slow","swing",function(){
			$email.text("EMAIL");
			$email.fadeIn("slow","swing");
		});
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>